// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class BrowserProfile {
    /**
     * Creates a new BrowserProfile instance.
     * @param {Partial<BrowserProfile>} [$$source = {}] - The source object to create the BrowserProfile.
     */
    constructor($$source = {}) {
        if (!("shortcutPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shortcutPath"] = "";
        }
        if (!("cacheDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cacheDir"] = "";
        }
        if (!("executablePath" in $$source)) {
            /**
             * Was ChromePath
             * @member
             * @type {string}
             */
            this["executablePath"] = "";
        }
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {GroupConfig[]}
             */
            this["groups"] = [];
        }
        if (!("currentGroup" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentGroup"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BrowserProfile}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField3_0($$parsedSource["groups"]);
        }
        return new BrowserProfile(/** @type {Partial<BrowserProfile>} */($$parsedSource));
    }
}

export class CustomArrangeParams {
    /**
     * Creates a new CustomArrangeParams instance.
     * @param {Partial<CustomArrangeParams>} [$$source = {}] - The source object to create the CustomArrangeParams.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("startX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startX"] = 0;
        }
        if (!("startY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startY"] = 0;
        }
        if (!("horizontalSpacing" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["horizontalSpacing"] = 0;
        }
        if (!("verticalSpacing" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["verticalSpacing"] = 0;
        }
        if (!("windowsPerRow" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowsPerRow"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomArrangeParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CustomArrangeParams}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CustomArrangeParams(/** @type {Partial<CustomArrangeParams>} */($$parsedSource));
    }
}

export class GroupConfig {
    /**
     * Creates a new GroupConfig instance.
     * @param {Partial<GroupConfig>} [$$source = {}] - The source object to create the GroupConfig.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("shortcutPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shortcutPath"] = "";
        }
        if (!("cacheDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cacheDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GroupConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupConfig(/** @type {Partial<GroupConfig>} */($$parsedSource));
    }
}

export class RandomInputConfig {
    /**
     * Creates a new RandomInputConfig instance.
     * @param {Partial<RandomInputConfig>} [$$source = {}] - The source object to create the RandomInputConfig.
     */
    constructor($$source = {}) {
        if (!("minValue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minValue"] = 0;
        }
        if (!("maxValue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxValue"] = 0;
        }
        if (!("isFloat" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isFloat"] = false;
        }
        if (!("decimalPlaces" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["decimalPlaces"] = 0;
        }
        if (!("overwrite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["overwrite"] = false;
        }
        if (!("delayed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["delayed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RandomInputConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RandomInputConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RandomInputConfig(/** @type {Partial<RandomInputConfig>} */($$parsedSource));
    }
}

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Legacy fields (kept for migration)
             * @member
             * @type {string | undefined}
             */
            this["shortcutPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["chromePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cacheDir"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GroupConfig[] | undefined}
             */
            this["groups"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["currentGroup"] = undefined;
        }
        if (!("profiles" in $$source)) {
            /**
             * New Browser Profiles
             * @member
             * @type {{ [_: string]: BrowserProfile }}
             */
            this["profiles"] = {};
        }
        if (!("browserType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["browserType"] = "";
        }
        if (!("screenSelection" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["screenSelection"] = "";
        }
        if (!("autoModifyShortcutIcon" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoModifyShortcutIcon"] = false;
        }
        if (!("windowOpenSpeed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowOpenSpeed"] = 0;
        }
        if (!("windowCloseInterval" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowCloseInterval"] = 0;
        }
        if (!("lastWindowNumbers" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastWindowNumbers"] = "";
        }
        if (!("windowNumbersHistory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["windowNumbersHistory"] = "";
        }
        if (!("lastEnvCreationNumbers" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastEnvCreationNumbers"] = "";
        }
        if (!("customArrangeParams" in $$source)) {
            /**
             * @member
             * @type {CustomArrangeParams}
             */
            this["customArrangeParams"] = (new CustomArrangeParams());
        }
        if (!("customURLs" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: string }}
             */
            this["customURLs"] = {};
        }
        if (!("syncToggleHotkey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["syncToggleHotkey"] = "";
        }
        if (!("windowConfig" in $$source)) {
            /**
             * @member
             * @type {WindowConfig}
             */
            this["windowConfig"] = (new WindowConfig());
        }
        if (!("syncConfig" in $$source)) {
            /**
             * @member
             * @type {SyncConfig}
             */
            this["syncConfig"] = (new SyncConfig());
        }
        if (!("randomInputConfig" in $$source)) {
            /**
             * @member
             * @type {RandomInputConfig}
             */
            this["randomInputConfig"] = (new RandomInputConfig());
        }
        if (!("closeBehavior" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["closeBehavior"] = "";
        }
        if (!("enableGroupMode" in $$source)) {
            /**
             * Configuration flags
             * @member
             * @type {boolean}
             */
            this["enableGroupMode"] = false;
        }
        if (!("enableAPIServer" in $$source)) {
            /**
             * OpenClaw API 集成
             * 是否启用 API 服务（默认关闭）
             * @member
             * @type {boolean}
             */
            this["enableAPIServer"] = false;
        }
        if (!("apiPort" in $$source)) {
            /**
             * API 端口（默认 18923）
             * @member
             * @type {number}
             */
            this["apiPort"] = 0;
        }
        if (!("apiToken" in $$source)) {
            /**
             * 访问令牌
             * @member
             * @type {string}
             */
            this["apiToken"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        const $$createField14_0 = $$createType4;
        const $$createField15_0 = $$createType5;
        const $$createField17_0 = $$createType6;
        const $$createField18_0 = $$createType7;
        const $$createField19_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField3_0($$parsedSource["groups"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField5_0($$parsedSource["profiles"]);
        }
        if ("customArrangeParams" in $$parsedSource) {
            $$parsedSource["customArrangeParams"] = $$createField14_0($$parsedSource["customArrangeParams"]);
        }
        if ("customURLs" in $$parsedSource) {
            $$parsedSource["customURLs"] = $$createField15_0($$parsedSource["customURLs"]);
        }
        if ("windowConfig" in $$parsedSource) {
            $$parsedSource["windowConfig"] = $$createField17_0($$parsedSource["windowConfig"]);
        }
        if ("syncConfig" in $$parsedSource) {
            $$parsedSource["syncConfig"] = $$createField18_0($$parsedSource["syncConfig"]);
        }
        if ("randomInputConfig" in $$parsedSource) {
            $$parsedSource["randomInputConfig"] = $$createField19_0($$parsedSource["randomInputConfig"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

export class SyncConfig {
    /**
     * Creates a new SyncConfig instance.
     * @param {Partial<SyncConfig>} [$$source = {}] - The source object to create the SyncConfig.
     */
    constructor($$source = {}) {
        if (!("mouseMoveThreshold" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mouseMoveThreshold"] = 0;
        }
        if (!("mouseMoveInterval" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["mouseMoveInterval"] = time$0.Duration.$zero;
        }
        if (!("keyboardInterval" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["keyboardInterval"] = time$0.Duration.$zero;
        }
        if (!("wheelEventThreshold" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["wheelEventThreshold"] = time$0.Duration.$zero;
        }
        if (!("enablePopupSync" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enablePopupSync"] = false;
        }
        if (!("enableZoomSync" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableZoomSync"] = false;
        }
        if (!("enableScrollSync" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableScrollSync"] = false;
        }
        if (!("enableKeyboardSync" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableKeyboardSync"] = false;
        }
        if (!("highPrecisionMode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["highPrecisionMode"] = false;
        }
        if (!("maxConcurrentEvents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxConcurrentEvents"] = 0;
        }
        if (!("eventBufferSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["eventBufferSize"] = 0;
        }
        if (!("maxRetryAttempts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxRetryAttempts"] = 0;
        }
        if (!("retryDelay" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["retryDelay"] = time$0.Duration.$zero;
        }
        if (!("errorThreshold" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["errorThreshold"] = 0;
        }
        if (!("enableEventDrivenMode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableEventDrivenMode"] = false;
        }
        if (!("disablePollingOperations" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["disablePollingOperations"] = false;
        }
        if (!("fastResponseMode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fastResponseMode"] = false;
        }
        if (!("cacheUpdateStrategy" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cacheUpdateStrategy"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncConfig(/** @type {Partial<SyncConfig>} */($$parsedSource));
    }
}

export class WindowConfig {
    /**
     * Creates a new WindowConfig instance.
     * @param {Partial<WindowConfig>} [$$source = {}] - The source object to create the WindowConfig.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("minWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minWidth"] = 0;
        }
        if (!("minHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minHeight"] = 0;
        }
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("maximized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["maximized"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowConfig(/** @type {Partial<WindowConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = GroupConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = BrowserProfile.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = CustomArrangeParams.createFrom;
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = WindowConfig.createFrom;
const $$createType7 = SyncConfig.createFrom;
const $$createType8 = RandomInputConfig.createFrom;
