// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RandomInputConfig {
    /**
     * Creates a new RandomInputConfig instance.
     * @param {Partial<RandomInputConfig>} [$$source = {}] - The source object to create the RandomInputConfig.
     */
    constructor($$source = {}) {
        if (!("minValue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minValue"] = 0;
        }
        if (!("maxValue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxValue"] = 0;
        }
        if (!("isFloat" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isFloat"] = false;
        }
        if (!("decimalPlaces" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["decimalPlaces"] = 0;
        }
        if (!("overwrite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["overwrite"] = false;
        }
        if (!("delayed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["delayed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RandomInputConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RandomInputConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RandomInputConfig(/** @type {Partial<RandomInputConfig>} */($$parsedSource));
    }
}

export class ScreenInfo {
    /**
     * Creates a new ScreenInfo instance.
     * @param {Partial<ScreenInfo>} [$$source = {}] - The source object to create the ScreenInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("primary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["primary"] = false;
        }
        if (!("left" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["left"] = 0;
        }
        if (!("top" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["top"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("workLeft" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["workLeft"] = 0;
        }
        if (!("workTop" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["workTop"] = 0;
        }
        if (!("workWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["workWidth"] = 0;
        }
        if (!("workHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["workHeight"] = 0;
        }
        if (!("deviceName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScreenInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScreenInfo(/** @type {Partial<ScreenInfo>} */($$parsedSource));
    }
}

export class TextInputConfig {
    /**
     * Creates a new TextInputConfig instance.
     * @param {Partial<TextInputConfig>} [$$source = {}] - The source object to create the TextInputConfig.
     */
    constructor($$source = {}) {
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("inputMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inputMethod"] = "";
        }
        if (!("overwrite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["overwrite"] = false;
        }
        if (!("delayed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["delayed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * 直接内容，用于从前端传递文本行
             * @member
             * @type {string[] | undefined}
             */
            this["directContent"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextInputConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TextInputConfig}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("directContent" in $$parsedSource) {
            $$parsedSource["directContent"] = $$createField4_0($$parsedSource["directContent"]);
        }
        return new TextInputConfig(/** @type {Partial<TextInputConfig>} */($$parsedSource));
    }
}

export class WindowArrangeParams {
    /**
     * Creates a new WindowArrangeParams instance.
     * @param {Partial<WindowArrangeParams>} [$$source = {}] - The source object to create the WindowArrangeParams.
     */
    constructor($$source = {}) {
        if (!("startX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startX"] = 0;
        }
        if (!("startY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startY"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("horizontalSpacing" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["horizontalSpacing"] = 0;
        }
        if (!("verticalSpacing" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["verticalSpacing"] = 0;
        }
        if (!("windowsPerRow" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowsPerRow"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowArrangeParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowArrangeParams}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowArrangeParams(/** @type {Partial<WindowArrangeParams>} */($$parsedSource));
    }
}

export class WindowArrangeResult {
    /**
     * Creates a new WindowArrangeResult instance.
     * @param {Partial<WindowArrangeResult>} [$$source = {}] - The source object to create the WindowArrangeResult.
     */
    constructor($$source = {}) {
        if (!("adjusted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["adjusted"] = false;
        }
        if (!("requestedWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestedWidth"] = 0;
        }
        if (!("requestedHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestedHeight"] = 0;
        }
        if (!("actualWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["actualWidth"] = 0;
        }
        if (!("actualHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["actualHeight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowArrangeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowArrangeResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowArrangeResult(/** @type {Partial<WindowArrangeResult>} */($$parsedSource));
    }
}

export class WindowInfo {
    /**
     * Creates a new WindowInfo instance.
     * @param {Partial<WindowInfo>} [$$source = {}] - The source object to create the WindowInfo.
     */
    constructor($$source = {}) {
        if (!("number" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["number"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("hwnd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hwnd"] = 0;
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("debugPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["debugPort"] = 0;
        }
        if (!("isRunning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRunning"] = false;
        }
        if (!("isMaster" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isMaster"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowInfo(/** @type {Partial<WindowInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
