// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BrowserCacheCleanResult {
    /**
     * Creates a new BrowserCacheCleanResult instance.
     * @param {Partial<BrowserCacheCleanResult>} [$$source = {}] - The source object to create the BrowserCacheCleanResult.
     */
    constructor($$source = {}) {
        if (!("requestedProfiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestedProfiles"] = 0;
        }
        if (!("cleanedProfiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cleanedProfiles"] = 0;
        }
        if (!("skippedRunning" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skippedRunning"] = 0;
        }
        if (!("missingProfiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["missingProfiles"] = 0;
        }
        if (!("failedProfiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failedProfiles"] = 0;
        }
        if (!("freedBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["freedBytes"] = 0;
        }
        if (!("profiles" in $$source)) {
            /**
             * @member
             * @type {BrowserCacheProfileResult[]}
             */
            this["profiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserCacheCleanResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BrowserCacheCleanResult}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField6_0($$parsedSource["profiles"]);
        }
        return new BrowserCacheCleanResult(/** @type {Partial<BrowserCacheCleanResult>} */($$parsedSource));
    }
}

export class BrowserCacheDetail {
    /**
     * Creates a new BrowserCacheDetail instance.
     * @param {Partial<BrowserCacheDetail>} [$$source = {}] - The source object to create the BrowserCacheDetail.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("relativePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relativePath"] = "";
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserCacheDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BrowserCacheDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrowserCacheDetail(/** @type {Partial<BrowserCacheDetail>} */($$parsedSource));
    }
}

export class BrowserCacheProfileResult {
    /**
     * Creates a new BrowserCacheProfileResult instance.
     * @param {Partial<BrowserCacheProfileResult>} [$$source = {}] - The source object to create the BrowserCacheProfileResult.
     */
    constructor($$source = {}) {
        if (!("windowNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowNumber"] = 0;
        }
        if (!("userDataDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userDataDir"] = "";
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("canClean" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canClean"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("details" in $$source)) {
            /**
             * @member
             * @type {BrowserCacheDetail[]}
             */
            this["details"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserCacheProfileResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BrowserCacheProfileResult}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField7_0($$parsedSource["details"]);
        }
        return new BrowserCacheProfileResult(/** @type {Partial<BrowserCacheProfileResult>} */($$parsedSource));
    }
}

export class BrowserCacheScanResult {
    /**
     * Creates a new BrowserCacheScanResult instance.
     * @param {Partial<BrowserCacheScanResult>} [$$source = {}] - The source object to create the BrowserCacheScanResult.
     */
    constructor($$source = {}) {
        if (!("scannedProfiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scannedProfiles"] = 0;
        }
        if (!("cleanableProfiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cleanableProfiles"] = 0;
        }
        if (!("skippedRunning" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skippedRunning"] = 0;
        }
        if (!("missingProfiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["missingProfiles"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalBytes"] = 0;
        }
        if (!("safeTargets" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["safeTargets"] = [];
        }
        if (!("profiles" in $$source)) {
            /**
             * @member
             * @type {BrowserCacheProfileResult[]}
             */
            this["profiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserCacheScanResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BrowserCacheScanResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("safeTargets" in $$parsedSource) {
            $$parsedSource["safeTargets"] = $$createField5_0($$parsedSource["safeTargets"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField6_0($$parsedSource["profiles"]);
        }
        return new BrowserCacheScanResult(/** @type {Partial<BrowserCacheScanResult>} */($$parsedSource));
    }
}

export class ExtensionRepairResult {
    /**
     * Creates a new ExtensionRepairResult instance.
     * @param {Partial<ExtensionRepairResult>} [$$source = {}] - The source object to create the ExtensionRepairResult.
     */
    constructor($$source = {}) {
        if (!("groupName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groupName"] = "";
        }
        if (!("donorWindowNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["donorWindowNumber"] = 0;
        }
        if (!("donorUserDataDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["donorUserDataDir"] = "";
        }
        if (!("extensionIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["extensionIds"] = [];
        }
        if (!("requestedTargets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestedTargets"] = 0;
        }
        if (!("repairedTargets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["repairedTargets"] = 0;
        }
        if (!("skippedRunning" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skippedRunning"] = 0;
        }
        if (!("missingTargets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["missingTargets"] = 0;
        }
        if (!("failedTargets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failedTargets"] = 0;
        }
        if (!("targets" in $$source)) {
            /**
             * @member
             * @type {ExtensionRepairTargetResult[]}
             */
            this["targets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionRepairResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExtensionRepairResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        const $$createField9_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensionIds" in $$parsedSource) {
            $$parsedSource["extensionIds"] = $$createField3_0($$parsedSource["extensionIds"]);
        }
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField9_0($$parsedSource["targets"]);
        }
        return new ExtensionRepairResult(/** @type {Partial<ExtensionRepairResult>} */($$parsedSource));
    }
}

export class ExtensionRepairTargetResult {
    /**
     * Creates a new ExtensionRepairTargetResult instance.
     * @param {Partial<ExtensionRepairTargetResult>} [$$source = {}] - The source object to create the ExtensionRepairTargetResult.
     */
    constructor($$source = {}) {
        if (!("windowNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowNumber"] = 0;
        }
        if (!("userDataDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userDataDir"] = "";
        }
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("repaired" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["repaired"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("extensionIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["extensionIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionRepairTargetResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExtensionRepairTargetResult}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensionIds" in $$parsedSource) {
            $$parsedSource["extensionIds"] = $$createField6_0($$parsedSource["extensionIds"]);
        }
        return new ExtensionRepairTargetResult(/** @type {Partial<ExtensionRepairTargetResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = BrowserCacheProfileResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = BrowserCacheDetail.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = ExtensionRepairTargetResult.createFrom;
const $$createType6 = $Create.Array($$createType5);
