// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RandomInputConfig {
    /**
     * Creates a new RandomInputConfig instance.
     * @param {Partial<RandomInputConfig>} [$$source = {}] - The source object to create the RandomInputConfig.
     */
    constructor($$source = {}) {
        if (!("IsFloat" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsFloat"] = false;
        }
        if (!("MinValue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["MinValue"] = 0;
        }
        if (!("MaxValue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["MaxValue"] = 0;
        }
        if (!("DecimalPlaces" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DecimalPlaces"] = 0;
        }
        if (!("Overwrite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Overwrite"] = false;
        }
        if (!("Delayed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Delayed"] = false;
        }
        if (!("InputMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["InputMethod"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RandomInputConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RandomInputConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RandomInputConfig(/** @type {Partial<RandomInputConfig>} */($$parsedSource));
    }
}

export class ScreenInfo {
    /**
     * Creates a new ScreenInfo instance.
     * @param {Partial<ScreenInfo>} [$$source = {}] - The source object to create the ScreenInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("primary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["primary"] = false;
        }
        if (!("left" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["left"] = 0;
        }
        if (!("top" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["top"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("workLeft" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["workLeft"] = 0;
        }
        if (!("workTop" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["workTop"] = 0;
        }
        if (!("workWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["workWidth"] = 0;
        }
        if (!("workHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["workHeight"] = 0;
        }
        if (!("scale" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scale"] = 0;
        }
        if (!("deviceName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScreenInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScreenInfo(/** @type {Partial<ScreenInfo>} */($$parsedSource));
    }
}

export class TextInputConfig {
    /**
     * Creates a new TextInputConfig instance.
     * @param {Partial<TextInputConfig>} [$$source = {}] - The source object to create the TextInputConfig.
     */
    constructor($$source = {}) {
        if (!("FilePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["FilePath"] = "";
        }
        if (!("Enter" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Enter"] = false;
        }
        if (!("InputMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["InputMethod"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextInputConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TextInputConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TextInputConfig(/** @type {Partial<TextInputConfig>} */($$parsedSource));
    }
}

export class WindowArrangeParams {
    /**
     * Creates a new WindowArrangeParams instance.
     * @param {Partial<WindowArrangeParams>} [$$source = {}] - The source object to create the WindowArrangeParams.
     */
    constructor($$source = {}) {
        if (!("startX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startX"] = 0;
        }
        if (!("startY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startY"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("horizontalSpacing" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["horizontalSpacing"] = 0;
        }
        if (!("verticalSpacing" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["verticalSpacing"] = 0;
        }
        if (!("windowsPerRow" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowsPerRow"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowArrangeParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowArrangeParams}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowArrangeParams(/** @type {Partial<WindowArrangeParams>} */($$parsedSource));
    }
}

export class WindowInfo {
    /**
     * Creates a new WindowInfo instance.
     * @param {Partial<WindowInfo>} [$$source = {}] - The source object to create the WindowInfo.
     */
    constructor($$source = {}) {
        if (!("Handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Handle"] = 0;
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Number" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Number"] = 0;
        }
        if (!("IsRunning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsRunning"] = false;
        }
        if (!("DebugPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DebugPort"] = 0;
        }
        if (!("PID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["PID"] = 0;
        }
        if (!("HWND" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["HWND"] = 0;
        }
        if (!("IsMaster" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsMaster"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowInfo(/** @type {Partial<WindowInfo>} */($$parsedSource));
    }
}
