// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class Rect {
    /**
     * Creates a new Rect instance.
     * @param {Partial<Rect>} [$$source = {}] - The source object to create the Rect.
     */
    constructor($$source = {}) {
        if (!("left" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["left"] = 0;
        }
        if (!("top" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["top"] = 0;
        }
        if (!("right" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["right"] = 0;
        }
        if (!("bottom" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bottom"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rect instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Rect}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Rect(/** @type {Partial<Rect>} */($$parsedSource));
    }
}

export class WindowInfo {
    /**
     * Creates a new WindowInfo instance.
     * @param {Partial<WindowInfo>} [$$source = {}] - The source object to create the WindowInfo.
     */
    constructor($$source = {}) {
        if (!("hwnd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hwnd"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("number" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["number"] = 0;
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["userDataDir"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["debugPort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["isMaster"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["isRunning"] = undefined;
        }
        if (!("clientRect" in $$source)) {
            /**
             * 窗口位置和尺寸信息
             * @member
             * @type {Rect}
             */
            this["clientRect"] = (new Rect());
        }
        if (!("windowRect" in $$source)) {
            /**
             * @member
             * @type {Rect}
             */
            this["windowRect"] = (new Rect());
        }
        if (!("popupWindows" in $$source)) {
            /**
             * 弹出窗口列表
             * @member
             * @type {number[]}
             */
            this["popupWindows"] = [];
        }
        if (!("lastSyncTime" in $$source)) {
            /**
             * 同步状态
             * @member
             * @type {time$0.Time}
             */
            this["lastSyncTime"] = null;
        }
        if (!("syncErrors" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["syncErrors"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowInfo}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clientRect" in $$parsedSource) {
            $$parsedSource["clientRect"] = $$createField8_0($$parsedSource["clientRect"]);
        }
        if ("windowRect" in $$parsedSource) {
            $$parsedSource["windowRect"] = $$createField9_0($$parsedSource["windowRect"]);
        }
        if ("popupWindows" in $$parsedSource) {
            $$parsedSource["popupWindows"] = $$createField10_0($$parsedSource["popupWindows"]);
        }
        return new WindowInfo(/** @type {Partial<WindowInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Rect.createFrom;
const $$createType1 = $Create.Array($Create.Any);
