// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChromeService 提供Chrome窗口管理功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as syncmanager$0 from "./syncmanager/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as utils$0 from "./utils/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddGroup 添加新分组
 * @param {{ [_: string]: any }} groupData
 * @returns {$CancellablePromise<void>}
 */
export function AddGroup(groupData) {
    return $Call.ByID(1160459613, groupData);
}

/**
 * ArrangeWindowsOnScreen 在指定屏幕上排列窗口
 * @param {number[]} windowIDs
 * @param {number} screenIndex
 * @param {utils$0.WindowArrangeParams} params
 * @returns {$CancellablePromise<void>}
 */
export function ArrangeWindowsOnScreen(windowIDs, screenIndex, params) {
    return $Call.ByID(2027737479, windowIDs, screenIndex, params);
}

/**
 * AutoArrangeWindows 自动排列选中的窗口
 * @param {number[]} windowIds
 * @returns {$CancellablePromise<utils$0.WindowArrangeResult | null>}
 */
export function AutoArrangeWindows(windowIds) {
    return $Call.ByID(4005952273, windowIds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * BatchOpenURL 批量打开网页到指定窗口 - 优化版，直接使用窗口信息
 * @param {string} url
 * @param {number[]} windowNumbers
 * @returns {$CancellablePromise<void>}
 */
export function BatchOpenURL(url, windowNumbers) {
    return $Call.ByID(1131803686, url, windowNumbers);
}

/**
 * BatchOpenURLToSelectedWindows 批量打开网页到选中的窗口 - 优化版，避免重新扫描进程
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function BatchOpenURLToSelectedWindows(url) {
    return $Call.ByID(2603984223, url);
}

/**
 * @param {string} groupName
 * @param {string} windowNumbers
 * @returns {$CancellablePromise<$models.BrowserCacheCleanResult | null>}
 */
export function CleanBrowserCaches(groupName, windowNumbers) {
    return $Call.ByID(1976963487, groupName, windowNumbers).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CleanIconCache 一键清理图标缓存
 * @returns {$CancellablePromise<void>}
 */
export function CleanIconCache() {
    return $Call.ByID(1325685333);
}

/**
 * ClearAllData 清理所有应用数据，删除配置文件并重启应用
 * @returns {$CancellablePromise<void>}
 */
export function ClearAllData() {
    return $Call.ByID(1253503707);
}

/**
 * CloseApplication 关闭应用程序
 * @returns {$CancellablePromise<void>}
 */
export function CloseApplication() {
    return $Call.ByID(3035988853);
}

/**
 * CloseWindows safely closes selected Chrome windows.
 * @param {number[]} windowIDs
 * @returns {$CancellablePromise<void>}
 */
export function CloseWindows(windowIDs) {
    return $Call.ByID(3973886170, windowIDs);
}

/**
 * CreateEnvironments 批量创建Chrome环境
 * @param {string} numbersStr
 * @returns {$CancellablePromise<void>}
 */
export function CreateEnvironments(numbersStr) {
    return $Call.ByID(2994672505, numbersStr);
}

/**
 * CustomArrangeWindows 自定义排列选中的窗口
 * @param {number[]} windowIds
 * @param {{ [_: string]: any }} params
 * @returns {$CancellablePromise<utils$0.WindowArrangeResult | null>}
 */
export function CustomArrangeWindows(windowIds, params) {
    return $Call.ByID(4246874097, windowIds, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteCustomURL 删除自定义网址
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCustomURL(name) {
    return $Call.ByID(1082142080, name);
}

/**
 * ExportSettings 导出配置文件
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function ExportSettings() {
    return $Call.ByID(974557440).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * FindBrowserPath 查找浏览器安装路径
 * @returns {$CancellablePromise<string>}
 */
export function FindBrowserPath() {
    return $Call.ByID(274267195);
}

/**
 * ForceResetInputManager 强制重置输入管理器状态（紧急恢复功能）
 * @returns {$CancellablePromise<void>}
 */
export function ForceResetInputManager() {
    return $Call.ByID(1625331282);
}

/**
 * GetAllImportedWindows 实现WindowInfoProvider接口，适配syncmanager的WindowInfo到utils的WindowInfo
 * @returns {$CancellablePromise<utils$0.WindowInfo[]>}
 */
export function GetAllImportedWindows() {
    return $Call.ByID(2830008545).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetCloseBehavior 获取关闭行为设置
 * @returns {$CancellablePromise<string>}
 */
export function GetCloseBehavior() {
    return $Call.ByID(818785137);
}

/**
 * GetEnvironmentCreationDebugInfo 获取环境创建调试信息
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetEnvironmentCreationDebugInfo() {
    return $Call.ByID(3644499438).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetEnvironmentInfo 获取环境信息
 * @param {number} windowNumber
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetEnvironmentInfo(windowNumber) {
    return $Call.ByID(2749173246, windowNumber).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetFilePreview 获取文件预览内容
 * @param {string} filePath
 * @returns {$CancellablePromise<string[]>}
 */
export function GetFilePreview(filePath) {
    return $Call.ByID(2218187961, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetGroups 获取所有分组列表
 * @returns {$CancellablePromise<config$0.GroupConfig[]>}
 */
export function GetGroups() {
    return $Call.ByID(1324578857).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetImportedWindows 获取已导入的窗口列表（用于前端显示）
 * @returns {$CancellablePromise<syncmanager$0.WindowInfo[]>}
 */
export function GetImportedWindows() {
    return $Call.ByID(4033624966).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetInputManagerStatus 获取输入管理器状态
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetInputManagerStatus() {
    return $Call.ByID(158982760).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetPresetURLs 获取预设网址列表
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetPresetURLs() {
    return $Call.ByID(2210782272).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetRandomInputConfig 获取随机输入配置
 * @returns {$CancellablePromise<config$0.RandomInputConfig | null>}
 */
export function GetRandomInputConfig() {
    return $Call.ByID(336312420).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetScreensInfo 获取屏幕信息
 * @returns {$CancellablePromise<utils$0.ScreenInfo[]>}
 */
export function GetScreensInfo() {
    return $Call.ByID(2667613890).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetSettings 实现SettingsGetter接口
 * @returns {$CancellablePromise<config$0.Settings | null>}
 */
export function GetSettings() {
    return $Call.ByID(2242583284).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetSettingsForFrontend() {
    return $Call.ByID(71255319).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetSyncStatus() {
    return $Call.ByID(2671241064).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetUpdatedWindowList 获取实时更新的窗口列表，自动移除已关闭的窗口
 * @returns {$CancellablePromise<syncmanager$0.WindowInfo[]>}
 */
export function GetUpdatedWindowList() {
    return $Call.ByID(2594213152).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * ImportSettings 导入配置文件
 * @param {{ [_: string]: any }} settingsData
 * @returns {$CancellablePromise<void>}
 */
export function ImportSettings(settingsData) {
    return $Call.ByID(1232543595, settingsData);
}

/**
 * @returns {$CancellablePromise<syncmanager$0.WindowInfo[]>}
 */
export function ImportWindows() {
    return $Call.ByID(1426095427).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<syncmanager$0.WindowInfo[]>}
 */
export function ImportWindowsWithIconSettings() {
    return $Call.ByID(3573306463).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * InputRandomNumbers 批量输入随机数字
 * @param {number[]} windowNumbers
 * @param {utils$0.RandomInputConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function InputRandomNumbers(windowNumbers, config) {
    return $Call.ByID(2292417548, windowNumbers, config);
}

/**
 * InputTextFromFile 从文件批量输入文本
 * @param {number[]} windowNumbers
 * @param {utils$0.TextInputConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function InputTextFromFile(windowNumbers, config) {
    return $Call.ByID(2766583972, windowNumbers, config);
}

/**
 * InputTextFromLines 从文本行数组批量输入文本
 * @param {number[]} windowNumbers
 * @param {string[]} lines
 * @param {string} inputMethod
 * @param {boolean} overwrite
 * @param {boolean} delayed
 * @returns {$CancellablePromise<void>}
 */
export function InputTextFromLines(windowNumbers, lines, inputMethod, overwrite, delayed) {
    return $Call.ByID(4072517273, windowNumbers, lines, inputMethod, overwrite, delayed);
}

/**
 * KeepOnlyCurrentTab 仅保留当前标签页，关闭其他标签页
 * @param {number[]} windowNumbers
 * @returns {$CancellablePromise<void>}
 */
export function KeepOnlyCurrentTab(windowNumbers) {
    return $Call.ByID(2799640500, windowNumbers);
}

/**
 * KeepOnlyNewTab 仅保留新标签页，关闭其他标签页
 * @param {number[]} windowNumbers
 * @returns {$CancellablePromise<void>}
 */
export function KeepOnlyNewTab(windowNumbers) {
    return $Call.ByID(1561095013, windowNumbers);
}

/**
 * MaximizeMainWindow 最大化/还原主窗口
 * @returns {$CancellablePromise<void>}
 */
export function MaximizeMainWindow() {
    return $Call.ByID(3766934620);
}

/**
 * MinimizeMainWindow 最小化主窗口
 * @returns {$CancellablePromise<void>}
 */
export function MinimizeMainWindow() {
    return $Call.ByID(18174258);
}

/**
 * MinimizeToTray 最小化应用程序到系统托盘
 * @returns {$CancellablePromise<void>}
 */
export function MinimizeToTray() {
    return $Call.ByID(3428760694);
}

/**
 * OpenWindows 打开Chrome窗口
 * @param {string} windowNumbers
 * @returns {$CancellablePromise<void>}
 */
export function OpenWindows(windowNumbers) {
    return $Call.ByID(1890887688, windowNumbers);
}

/**
 * @returns {$CancellablePromise<syncmanager$0.WindowInfo[]>}
 */
export function RefreshWindowList() {
    return $Call.ByID(3765254442).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * RemoveGroup 删除分组
 * @param {string} groupName
 * @returns {$CancellablePromise<void>}
 */
export function RemoveGroup(groupName) {
    return $Call.ByID(1686877098, groupName);
}

/**
 * @param {string} targetWindowNumbers
 * @param {number} donorWindowNumber
 * @returns {$CancellablePromise<$models.ExtensionRepairResult | null>}
 */
export function RepairExtensionsFromDonor(targetWindowNumbers, donorWindowNumber) {
    return $Call.ByID(2077788152, targetWindowNumbers, donorWindowNumber).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * ResetCloseBehavior 重置关闭行为设置
 * @returns {$CancellablePromise<void>}
 */
export function ResetCloseBehavior() {
    return $Call.ByID(898912588);
}

/**
 * RestartApplication 重启应用程序
 * @returns {$CancellablePromise<void>}
 */
export function RestartApplication() {
    return $Call.ByID(3028572668);
}

/**
 * RestoreDefaultIcons 一键还原快捷方式图标（支持所有分组）
 * @returns {$CancellablePromise<void>}
 */
export function RestoreDefaultIcons() {
    return $Call.ByID(1778170806);
}

/**
 * SaveCustomURL 保存自定义网址
 * @param {string} name
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function SaveCustomURL(name, url) {
    return $Call.ByID(672697714, name, url);
}

/**
 * SaveFileDialog 打开文件保存对话框
 * @param {string} defaultFileName
 * @param {string} fileFilter
 * @returns {$CancellablePromise<string>}
 */
export function SaveFileDialog(defaultFileName, fileFilter) {
    return $Call.ByID(1273097564, defaultFileName, fileFilter);
}

/**
 * SaveJSONFile 保存JSON数据到文件
 * @param {string} filePath
 * @param {string} jsonData
 * @returns {$CancellablePromise<void>}
 */
export function SaveJSONFile(filePath, jsonData) {
    return $Call.ByID(1766986162, filePath, jsonData);
}

/**
 * SaveRandomInputConfig 保存随机输入配置到设置文件
 * @param {utils$0.RandomInputConfig} utilsConfig
 * @returns {$CancellablePromise<void>}
 */
export function SaveRandomInputConfig(utilsConfig) {
    return $Call.ByID(2220365913, utilsConfig);
}

/**
 * SaveWindowSize 保存窗口尺寸
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function SaveWindowSize(width, height) {
    return $Call.ByID(1121303415, width, height);
}

/**
 * @param {string} groupName
 * @param {string} windowNumbers
 * @returns {$CancellablePromise<$models.BrowserCacheScanResult | null>}
 */
export function ScanBrowserCaches(groupName, windowNumbers) {
    return $Call.ByID(3628591649, groupName, windowNumbers).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * SelectAllWindows API 触发的全选操作
 * @param {boolean} selected
 * @returns {$CancellablePromise<void>}
 */
export function SelectAllWindows(selected) {
    return $Call.ByID(2742265807, selected);
}

/**
 * SelectFile 打开文件选择对话框
 * @param {string} title
 * @param {string} filter
 * @returns {$CancellablePromise<string>}
 */
export function SelectFile(title, filter) {
    return $Call.ByID(1996287985, title, filter);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectFolder() {
    return $Call.ByID(600237963);
}

/**
 * SetCloseBehavior 设置关闭行为
 * @param {string} behavior
 * @returns {$CancellablePromise<void>}
 */
export function SetCloseBehavior(behavior) {
    return $Call.ByID(1114001717, behavior);
}

/**
 * SetCurrentGroup 设置当前分组
 * @param {string} groupName
 * @returns {$CancellablePromise<void>}
 */
export function SetCurrentGroup(groupName) {
    return $Call.ByID(3162523165, groupName);
}

/**
 * SetGroupMode 设置分组模式开关
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetGroupMode(enabled) {
    return $Call.ByID(2927299807, enabled);
}

/**
 * SetMasterWindow 设置主控窗口（公共接口）
 * @param {number} windowNumber
 * @returns {$CancellablePromise<void>}
 */
export function SetMasterWindow(windowNumber) {
    return $Call.ByID(1571844347, windowNumber);
}

/**
 * ShowMainWindow 显示主窗口（智能激活版本）
 * @returns {$CancellablePromise<void>}
 */
export function ShowMainWindow() {
    return $Call.ByID(784905171);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShutdownHotkeys() {
    return $Call.ByID(1723190736);
}

/**
 * StartSync 开始同步 - 异步执行，立即返回
 * @param {number} masterWindowNumber
 * @param {number[]} slaveWindowNumbers
 * @returns {$CancellablePromise<void>}
 */
export function StartSync(masterWindowNumber, slaveWindowNumbers) {
    return $Call.ByID(1143311418, masterWindowNumber, slaveWindowNumbers);
}

/**
 * StopSync 停止同步 - 异步执行，立即返回
 * @returns {$CancellablePromise<void>}
 */
export function StopSync() {
    return $Call.ByID(1564560144);
}

/**
 * TestEnvironmentCreation 测试环境创建（用于调试）
 * @param {number} testNumber
 * @returns {$CancellablePromise<void>}
 */
export function TestEnvironmentCreation(testNumber) {
    return $Call.ByID(1339495837, testNumber);
}

/**
 * UpdateGroup 更新分组
 * @param {string} oldName
 * @param {{ [_: string]: any }} groupData
 * @returns {$CancellablePromise<void>}
 */
export function UpdateGroup(oldName, groupData) {
    return $Call.ByID(1093251281, oldName, groupData);
}

/**
 * UpdateSettings 更新设置
 * @param {{ [_: string]: any }} settingsMap
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSettings(settingsMap) {
    return $Call.ByID(1257069227, settingsMap);
}

/**
 * ValidateEnvironmentConfig 验证环境配置
 * @returns {$CancellablePromise<void>}
 */
export function ValidateEnvironmentConfig() {
    return $Call.ByID(2220172848);
}

/**
 * ValidateRandomInputConfig 验证随机数输入配置
 * @param {utils$0.RandomInputConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function ValidateRandomInputConfig(config) {
    return $Call.ByID(3916684924, config);
}

/**
 * ValidateTextInputConfig 验证文本输入配置
 * @param {utils$0.TextInputConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function ValidateTextInputConfig(config) {
    return $Call.ByID(3968419872, config);
}

// Private type creation functions
const $$createType0 = utils$0.WindowArrangeResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.BrowserCacheCleanResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = utils$0.WindowInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = config$0.GroupConfig.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = syncmanager$0.WindowInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = config$0.RandomInputConfig.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = utils$0.ScreenInfo.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = config$0.Settings.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $models.ExtensionRepairResult.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = $models.BrowserCacheScanResult.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
